//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT
    {
        public int shipment_id { get; set; }
        public int shipper_id { get; set; }
        public string shipment_description { get; set; }
        public decimal shipment_weight { get; set; }
        public int shipment_rate_id { get; set; }
        public int carrier_id { get; set; }
    
        public virtual CARRIER CARRIER { get; set; }
        public virtual SHIPMENT_RATE SHIPMENT_RATE { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
    }
}
